FROM harbor.prd.afip.gob.ar/dockerhub/library/python:3.8.16-slim
# FROM python:3.8.16-slim 
ARG http_proxy
ARG https_proxy
ARG no_proxy
ARG oracle_version
RUN echo "$http_proxy"
RUN echo "$https_proxy"
RUN echo "$no_proxy"
RUN echo "oracle_version: $oracle_version"

# Configuracion del timezone
RUN echo "America/Buenos_Aires" > /etc/timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/America/Buenos_Aires /etc/localtime

###############################################################################
# Instalacion de librería Oracle para python si es necesario (oracle version = 11)
WORKDIR /opt/oracle
RUN if [ "$oracle_version" -le 11 ]; then \
        echo "Instalo instantclient" \
        && apt-get update && apt-get install -y libaio1 wget unzip \
        && wget --quiet --no-proxy --no-check-certificate https://nexus.cloudint.afip.gob.ar/nexus/repository/fisca-infraestructura-raw/oracle/instantclient/instantclient-basiclite-linuxx64.zip \
        && unzip -q instantclient-basiclite-linuxx64.zip \
        && rm -f instantclient-basiclite-linuxx64.zip \
        && mv /opt/oracle/instantclient* /opt/oracle/instantclient \
        && cd /opt/oracle/instantclient \
        && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci \
        && echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf \
        && ldconfig \
        # Se crea un link simbólico
        && ln -s /opt/oracle/instantclient instantclient \
        # Variable de ambiente del cliente oracle
        && export LD_LIBRARY_PATH="/app/instantclient"; \
    else \
        echo "Instantclient no se instalará (oracle_version != 11)"; \
    fi

# Configuración y actualización de pip
RUN echo "[global]\ntrusted-host =  pypi.python.org\n                pypi.org\n                files.pythonhosted.org\n                nexus.cloudint.afip.gob.ar\n                cloudint.afip.gob.ar\n                nexus.cloudhomo.afip.gob.ar\n                download.oracle.com \n\nindex-url = https://nexus.cloudint.afip.gob.ar/nexus/repository/sandbox-pypi/simple \nextra-index-url = https://nexus.cloudhomo.afip.gob.ar/nexus/repository/pypi-proxy/simple\n"  > /etc/pip.conf
RUN python -m pip install --upgrade pip
RUN pip install pipenv 
###############################################################################

# Implementación de la aplicación
WORKDIR /app

COPY Pipfile* ./
RUN pipenv install --system --deploy --ignore-pipfile 
RUN pip uninstall -y pipenv

COPY ./app ./app
COPY version.yaml .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

